monolog:
    channels:
        - deprecation 
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: stream
            channels: [deprecation]
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info

when:
    '@prod':
        monolog:
            handlers:
                main:
                    type: fingers_crossed
                    action_level: error
                    handler: nested
                    buffer_size: 50
                nested:
                    type: stream
                    path: "%kernel.logs_dir%/%kernel.environment%.log"
                    level: error
                deprecation:
                    type: null
