@startuml trick

class Trick {
  id: number
  name: string
  description: string
  group: string
  imageLink: imagelink[]
  videoLink: videolink[]
  author: User
  dateOfCreation: date
  dateOfLastModified: date
  discussionChannel: string
  +create(name: string, description: string, group: string, imageLink: string, videoLink: string): void
  +modify(name: string, description: string, group: string, imageLink: string, videoLink: string): void
  +delete(id): void
  +edit(): void

}

@enduml
