@startuml resetPassword

actor User
boundary Form
database DB

User -> Form : Fills in email
Form -> DB : Check email
DB -> Form : Email exists?
Form --> User : Error: email not found
User -> User: recieves email with token
User -> Form: Fills in token
Form -> DB: Token valid ?
User -> Form: Fills in new password
Form -> DB: replace password



@enduml
