@startuml trick

class Trick {
  id: string
  name: string
  description: string
  group: string
  imageLink: string
  videoLink: string
  author: string
  dateOfCreation: date
  dateOfLastModified: date
  discussionChannel: string
  deleted: boolean
   read(id: string): void
  create(name: string, description: string, group: string, imageLink: string, videoLink: string): void
  update(name: string, description: string, group: string, imageLink: string, videoLink: string): void
  delete(id: string): void

}

@enduml
