@startuml user

class User {
  username: string
  firstname: string
  lastname: string
  imageLink: string
  create(username: string, firstname: string, lastname: string, imageLink: string): void
  delete(): void
}

@enduml
