@startuml createTrick

actor User
actor Database

usecase FillOutForm as "Fill out form"
usecase CheckTrickName as "Check if trick name exists"
usecase ValidateLinks as "Check if at least one image and video links"
usecase SetAttributes as "Set attributes\nand create entry"
usecase DisplayValidation as "Display validation message"


User --> FillOutForm
FillOutForm --> CheckTrickName : Controller
CheckTrickName --> ValidateLinks : Controller
ValidateLinks --> SetAttributes : Controller
SetAttributes --> Database
Database --> DisplayValidation
DisplayValidation --> User

@enduml
