@startuml resetPassword

actor User
database DB
usecase ResetPassword

User -> ResetPassword: Provide token
User -> ResetPassword: Provide email address
ResetPassword -> DB: checks if email exists
DB -> ResetPassword: generates token
ResetPassword -> User: Send email with token

@enduml
