@startuml resetPassword

actor User
database DB
usecase ResetPassword

User -> ResetPassword: Provide token through clicking on link in email
User -> ResetPassword: Provide email address
ResetPassword -> DB: checks if email exists
DB -> ResetPassword: generates token
ResetPassword -> User: Send email link to website and token
ResetPassword -> DB: Sets new password

@enduml
